version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=wolf

  express-server:
    build:
      context: ./express-server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - ./express-server:/app
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=wolf
      - PORT=8000
      - HOST=localhost

    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "5000:80"
